// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWIXj0ZGlZVu758SigcJZTkUBF6FqI3p4',
    appId: '1:557242646634:web:531fc45669260d96c08a13',
    messagingSenderId: '557242646634',
    projectId: 'easybookapp-a9894',
    authDomain: 'easybookapp-a9894.firebaseapp.com',
    storageBucket: 'easybookapp-a9894.firebasestorage.app',
    measurementId: 'G-N6YCVJX8PP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqFwzEjlr1HipcmjTBp8dA3_en2bTLBd4',
    appId: '1:557242646634:android:415a1f36b479b24fc08a13',
    messagingSenderId: '557242646634',
    projectId: 'easybookapp-a9894',
    storageBucket: 'easybookapp-a9894.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzOFQd2NA7rVhehkHwJfQWZ9-HFFSCZLs',
    appId: '1:557242646634:ios:bc5d77c8db0ef50ac08a13',
    messagingSenderId: '557242646634',
    projectId: 'easybookapp-a9894',
    storageBucket: 'easybookapp-a9894.firebasestorage.app',
    iosBundleId: 'com.example.asayBookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzOFQd2NA7rVhehkHwJfQWZ9-HFFSCZLs',
    appId: '1:557242646634:ios:bc5d77c8db0ef50ac08a13',
    messagingSenderId: '557242646634',
    projectId: 'easybookapp-a9894',
    storageBucket: 'easybookapp-a9894.firebasestorage.app',
    iosBundleId: 'com.example.asayBookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWIXj0ZGlZVu758SigcJZTkUBF6FqI3p4',
    appId: '1:557242646634:web:d54828f6b0af3e06c08a13',
    messagingSenderId: '557242646634',
    projectId: 'easybookapp-a9894',
    authDomain: 'easybookapp-a9894.firebaseapp.com',
    storageBucket: 'easybookapp-a9894.firebasestorage.app',
    measurementId: 'G-V5E7ERHG47',
  );
}
